// Signal configuration matching your CAN message format
// Format: [size_bytes, datatype, units, min, max, "subsystem;description"]
export const SIGNAL_CONFIG = {
  // PDC Signals
  accelerator_pedal: [4, "float", "%", 0, 1, "PDC;Sensors"],
  speed: [4, "float", "mph", 0, 100, "PDC;Motor Controller I/O"],
  eco: [1, "bool", "", 0, 1, "PDC;Motor Controller I/O"],
  mc_status: [1, "uint8", "", 0, 0, "PDC;Motor Controller I/O"],
  regen_brake: [4, "float", "%", 0, 1, "PDC;Sensors"],
  park_brake: [1, "bool", "", 0, 1, "PDC;Sensors"],
  brake_led_en: [1, "bool", "", 0, 1, "PDC;Lights"],
  main_5V_bus: [4, "float", "V", 0, 100, "PDC;Sensors"],
  main_12V_bus: [4, "float", "V", 0, 100, "PDC;Sensors"],
  main_5V_current: [4, "float", "A", 0, 100, "PDC;Sensors"],

  // MCC Signals
  mcc_state: [1, "uint8", "", 0, 7, "MCC;Firmware"],
  crz_pwr_mode: [1, "bool", "", 0, 1, "MCC;Driver Buttons/Switches"],
  crz_pwr_setpt: [4, "float", "W", 0, 100, "MCC;Firmware"],
  crz_spd_setpt: [4, "float", "mph", 0, 100, "MCC;Firmware"],
  main_telem: [1, "bool", "", 0, 1, "MCC;Driver Buttons/Switches"],
  foot_brake: [1, "bool", "", 0, 1, "MCC;Sensors"],
  motor_current: [4, "float", "A", 0, 100, "MCC;Sensors"],
  motor_power: [4, "float", "W", 0, 100, "MCC;Firmware"],

  // Steering Wheel Signals
  fr_telem: [1, "bool", "", 0, 1, "Steering Wheel;Driver Buttons/Switches"],
  crz_spd_mode: [1, "bool", "", 0, 1, "Steering Wheel;Driver Buttons/Switches"],
  l_turn_led_en: [1, "bool", "", 0, 1, "Steering Wheel;Lights"],
  r_turn_led_en: [1, "bool", "", 0, 1, "Steering Wheel;Lights"],

  // High Voltage Signals
  driver_eStop: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  external_eStop: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  crash: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  discharge_enable: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  discharge_enabled: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  charge_enable: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  charge_enabled: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  isolation: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  mcu_hv_en: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  mcu_stat_fdbk: [1, "bool", "", 0, 0, "High Voltage;Shutdown"],
  mppt_contactor: [1, "bool", "", 1, 1, "High Voltage;MPS"],
  motor_controller_contactor: [1, "bool", "", 1, 1, "High Voltage;MPS"],
  low_contactor: [1, "bool", "", 1, 1, "High Voltage;MPS"],
  dcdc_current: [4, "float", "A", 0, 100, "High Voltage;MPS"],
  dcdc_deg: [1, "bool", "", 1, 1, "High Voltage;MPS"],
  use_dcdc: [1, "bool", "", 0, 0, "High Voltage;MPS"],
  use_supp: [1, "bool", "", 0, 0, "High Voltage;MPS"],
  bms_mpio1: [1, "bool", "", 0, 1, "High Voltage;IO"],

  // Battery Signals
  pack_temp: [1, "float", "degC", 0, 55, "Battery;BMS"],
  pack_internal_temp: [1, "float", "degC", 0, 100, "Battery;BMS"],
  pack_current: [2, "float", "A", -24.4, 48.8, "Battery;BMS"],
  pack_voltage: [2, "float", "V", 77.5, 113.15, "Battery;BMS"],
  pack_power: [4, "float", "W", -2760.86, 5521.72, "Battery;Firmware"],
  populated_cells: [1, "uint16", "", 0, 100, "Battery;BMS"],
  soc: [1, "float", "%", 0, 100, "Battery;BMS"],
  soh: [1, "float", "%", 0, 100, "Battery;BMS"],
  pack_amphours: [2, "float", "Ah", 57, 57, "Battery;BMS"],
  adaptive_total_capacity: [2, "float", "Ah", 0, 100, "Battery;BMS"],
  fan_speed: [1, "uint8", "", 0, 6, "Battery;BMS"],
  pack_resistance: [2, "float", "mOhm", 0, 100, "Battery;BMS"],
  bms_input_voltage: [2, "float", "V", 12, 24, "Battery;BMS"],
  supplemental_current: [4, "float", "A", 0, 100, "Battery;Supplemental"],
  supplemental_voltage: [4, "float", "V", 0, 100, "Battery;Supplemental"],
  supplemental_deg: [1, "bool", "", 1, 1, "Battery;Supplemental"],
  est_supplemental_soc: [4, "float", "%", 0, 100, "Battery;Supplemental"],
  bps_fault: [1, "bool", "", 0, 0, "Battery;BMS"],

  // Battery Failsafes
  voltage_failsafe: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],
  current_failsafe: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],
  relay_failsafe: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],
  cell_balancing_active: [1, "bool", "", 1, 1, "Battery;BMS Failsafes"],
  charge_interlock_failsafe: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],
  thermistor_b_value_table_invalid: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],
  input_power_supply_failsafe: [1, "bool", "", 0, 0, "Battery;BMS Failsafes"],

  // Battery Faults
  discharge_limit_enforcement_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  charger_safety_relay_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  internal_hardware_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  internal_heatsink_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  internal_software_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  highest_cell_voltage_too_high_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  lowest_cell_voltage_too_low_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  pack_too_hot_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  high_voltage_interlock_signal_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  precharge_circuit_malfunction: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  abnormal_state_of_charge_behavior: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  internal_communication_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  cell_balancing_stuck_off_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  weak_cell_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  low_cell_voltage_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  open_wiring_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  current_sensor_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  highest_cell_voltage_over_5V_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  cell_asic_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  weak_pack_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  fan_monitor_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  thermistor_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  external_communication_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  redundant_power_supply_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  high_voltage_isolation_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  input_power_supply_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],
  charge_limit_enforcement_fault: [1, "bool", "", 0, 0, "Battery;BMS Faults"],

  // Cell Voltages
  cell_group1_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group2_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group3_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group4_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group5_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group6_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group7_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group8_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group9_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group10_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group11_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group12_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group13_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group14_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group15_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group16_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group17_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group18_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group19_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group20_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group21_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group22_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group23_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group24_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group25_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group26_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group27_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group28_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group29_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group30_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],
  cell_group31_voltage: [2, "float", "V", 2.5, 3.65, "Battery;Cell Voltages"],

  // Solar Array Signals
  mppt_mode: [1, "bool", "", 0, 1, "Solar Array;MPPT"],
  mppt_current_out: [4, "float", "A", 0, 7, "Solar Array;Sensors"],
  string1_temp: [4, "float", "degC", 20, 50, "Solar Array;Sensors"],
  string2_temp: [4, "float", "degC", 20, 50, "Solar Array;Sensors"],
  string3_temp: [4, "float", "degC", 20, 50, "Solar Array;Sensors"],
  string1_V_in: [4, "float", "V", 0, 60, "Solar Array;Sensors"],
  string2_V_in: [4, "float", "V", 0, 60, "Solar Array;Sensors"],
  string3_V_in: [4, "float", "V", 0, 60, "Solar Array;Sensors"],
  string1_I_in: [4, "float", "A", 0, 7, "Solar Array;Sensors"],
  string2_I_in: [4, "float", "A", 0, 7, "Solar Array;Sensors"],
  string3_I_in: [4, "float", "A", 0, 7, "Solar Array;Sensors"],

  // Main IO Signals
  air_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  brake_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  dcdc_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  mainIO_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  motor_controller_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  motor_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  road_temp: [4, "float", "degC", 0, 100, "Main IO;Sensors"],
  headlights_led_en: [1, "bool", "", 0, 1, "Main IO;Lights"],
  hazards: [1, "bool", "", 0, 0, "Main IO;Lights"],
  main_24V_bus: [4, "float", "V", 0, 100, "Main IO;Sensors"],
  main_12V_current: [4, "float", "A", 0, 100, "Main IO;Sensors"],
  main_24V_current: [4, "float", "A", 0, 100, "Main IO;Sensors"],
  bms_can_heartbeat: [1, "bool", "", 1, 1, "Main IO;Firmware"],
  hv_can_heartbeat: [1, "bool", "", 1, 1, "Main IO;Firmware"],
  mainIO_heartbeat: [1, "bool", "", 1, 1, "Main IO;Firmware"],
  mcc_can_heartbeat: [1, "bool", "", 1, 1, "Main IO;Firmware"],
  mppt_can_heartbeat: [1, "bool", "", 1, 1, "Main IO;Firmware"],

  // Software Signals
  tstamp_ms: [2, "uint16", "ms", 0, 999, "Software;Timestamp"],
  tstamp_sc: [1, "uint8", "s", 0, 59, "Software;Timestamp"],
  tstamp_mn: [1, "uint8", "min", 0, 59, "Software;Timestamp"],
  tstamp_hr: [1, "uint8", "hr", 0, 23, "Software;Timestamp"],
  tstamp_unix: [8, "uint64", "ms", 0, 0, "Software;Timestamp"],
  lat: [4, "float", "Degree", 0, 0, "Software;GPS"],
  lon: [4, "float", "Degree", 0, 0, "Software;GPS"],
  elev: [4, "float", "meter", 0, 0, "Software;GPS"],
};

// Helper to get signals grouped by category
export const getSignalsByCategory = () => {
  const categories = {};
  Object.entries(SIGNAL_CONFIG).forEach(([name, config]) => {
    const category = config[5].split(';')[0];
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(name);
  });
  return categories;
};
